[project]
name = ""
version = ""
description = ""
authors = [
    {name = "", email = ""},
]
dependencies = [
    "django>=4.2.4",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

